// apps/web/src/app/auth/register/page.tsx
"use client";

import React, { useState } from "react";
import { View, Text } from "react-native";
import { Input, Button, Card } from "@alldare/ui";
import { useAuth, useAuthContext } from "@alldare/hooks";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function RegisterPage() {
  const [login, setLogin] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  
  const { register } = useAuth();
  const { login: setAuthSession } = useAuthContext();
  const router = useRouter();

  const handleRegister = async () => {
    if (!login || !password || !confirmPassword) {
      setError("All fields are required.");
      return;
    }

    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }

    setIsLoading(true);
    setError("");

    try {
      await register({ login, password });
      // For simplicity, we could auto-login here or redirect to login
      // Let's assume registration returns a success and we redirect to login
      router.push("/auth/login?registered=true");
    } catch (e: any) {
      setError(e.message || "Registration failed.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <View className="flex-1 items-center justify-center p-4 bg-black min-h-screen">
      <Card className="w-full max-w-md">
        <Text className="text-3xl font-bold text-white mb-2">Create Account</Text>
        <Text className="text-slate-400 mb-8 text-base">Join the Alldare platform</Text>

        <Input
          label="Login (Username or Email)"
          value={login}
          onChangeText={setLogin}
          placeholder="Choose a login"
        />

        <Input
          label="Password"
          value={password}
          onChangeText={setPassword}
          placeholder="Create a password"
          secureTextEntry
        />

        <Input
          label="Confirm Password"
          value={confirmPassword}
          onChangeText={setConfirmPassword}
          placeholder="Confirm your password"
          secureTextEntry
        />

        {error ? (
          <Text className="text-red-500 mb-4 text-center text-sm">{error}</Text>
        ) : null}

        <Button
          title="Sign Up"
          onPress={handleRegister}
          loading={isLoading}
          className="mt-2"
        />

        <View className="mt-8 items-center">
          <Text className="text-slate-400 text-sm">
            Already have an account?{" "}
            <Link href="/auth/login" className="text-blue-500 font-bold">
              Sign In
            </Link>
          </Text>
        </View>
      </Card>
    </View>
  );
}

// src/app/features/auth/register/register.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { InputComponent } from '../../../shared/components/input/input.component';
import { ButtonComponent } from '../../../shared/components/button/button.component';
import { CardComponent } from '../../../shared/components/card/card.component';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-register',
  imports: [
    CommonModule,
    RouterLink,
    FormsModule,
    InputComponent,
    ButtonComponent,
    CardComponent
  ],
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss'
})
export class RegisterComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  loginValue = signal('');
  passwordValue = signal('');
  confirmPasswordValue = signal('');
  error = signal('');
  isLoading = signal(false);

  handleRegister() {
    const login = this.loginValue();
    const password = this.passwordValue();
    const confirm = this.confirmPasswordValue();

    if (!login || !password || !confirm) {
      this.error.set('All fields are required.');
      return;
    }

    if (password !== confirm) {
      this.error.set('Passwords do not match.');
      return;
    }

    this.isLoading.set(true);
    this.error.set('');

    this.authService.register({ login, password }).subscribe({
      next: () => {
        this.router.navigate(['/auth/login'], { queryParams: { registered: 'true' } });
      },
      error: (e) => {
        this.error.set(e.error?.message || 'Registration failed.');
        this.isLoading.set(false);
      }
    });
  }

  handleGoogleSso() {
    window.location.href = this.authService.getGoogleSsoUrl();
  }
}

<div class="register-page-wrapper flex items-center justify-center p-4 md:p-8 bg-black min-h-screen">
  <app-card className="w-full max-w-md border-slate-800 shadow-2xl">
    <h1 class="text-3xl md:text-4xl font-black text-white mb-2 tracking-tighter uppercase">Create Account</h1>
    <p class="text-slate-400 mb-8 md:mb-10 text-sm md:text-base font-medium">Join the Alldare creator community</p>

    <app-input
      label="Login"
      [value]="loginValue()"
      (valueChange)="loginValue.set($event)"
      placeholder="Choose a username"
    ></app-input>

    <app-input
      label="Password"
      [value]="passwordValue()"
      (valueChange)="passwordValue.set($event)"
      placeholder="••••••••"
      [secureTextEntry]="true"
    ></app-input>

    <app-input
      label="Confirm Password"
      [value]="confirmPasswordValue()"
      (valueChange)="confirmPasswordValue.set($event)"
      placeholder="Repeat your password"
      [secureTextEntry]="true"
    ></app-input>

    @if (error()) {
      <p class="text-red-500 mb-6 text-center text-sm font-medium bg-red-500/10 p-3 rounded-xl border border-red-500/20">
        {{ error() }}
      </p>
    }

    <app-button
      title="Sign Up"
      (onPress)="handleRegister()"
      [loading]="isLoading()"
      className="mt-2 w-full shadow-lg h-12"
    ></app-button>

    <div class="mt-8 mb-6 flex flex-row justify-center items-center">
      <div class="h-[1px] flex-1 bg-slate-800"></div>
      <span class="mx-6 text-slate-600 text-xs font-bold tracking-widest uppercase">Or join with</span>
      <div class="h-[1px] flex-1 bg-slate-800"></div>
    </div>

    <app-button
      title="Continue with Google"
      variant="outline"
      (onPress)="handleGoogleSso()"
      className="w-full h-12 flex flex-row items-center gap-2"
    >
      <svg class="w-5 h-5" viewBox="0 0 24 24">
        <path fill="currentColor" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
        <path fill="currentColor" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
        <path fill="currentColor" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z" />
        <path fill="currentColor" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
      </svg>
    </app-button>

    <div class="mt-8 md:mt-10 text-center border-t border-slate-800 pt-8">
      <p class="text-slate-500 text-sm font-medium">
        Already have an account?
        <a routerLink="/auth/login" class="text-blue-500 font-bold ml-1 hover:underline transition-all">
          Sign In
        </a>
      </p>
    </div>
  </app-card>
</div>
